export const BASE_MOONS = ["Jupiter", "Callisto", "Europa", "Ganymede", "IO", "Moon"]

export const PLANET_NAV = [
    "Mercury",
    "Venus",
    "Earth",
    "Mars",
    "Jupiter",
    "Saturn",
    "Uranus",
    "Neptune",
]

export const DEFAULT_SYSTEM = {
    Jupiter: { radius: 1, position: [0, 0, 0], color: 0xd68b4a },
    Europa: {
        radius: 0.02,
        position: [1.5266029, -0.21509023, -1.41535184],
        color: 0xd8d2bd,
    },
    Ganymede: {
        radius: 0.02,
        position: [3.46876701, -0.03102102, 1.47353192],
        color: 0x8f7d68,
    },
    IO: {
        radius: 0.02,
        position: [0.78437079, -0.03102102, 1.74507503],
        color: 0xe0b46a,
    },
    Callisto: {
        radius: 0.02,
        position: [-3.08223687, -0.03102102, -1.09343633],
        color: 0x6f6258,
    },
}

export const getPlanetConfigs = (config) => [
    {
        name: "Mercury",
        displayname: "Mercúrio",
        texture: config.mercuryTexture,
        dist: config.mercuryDist ?? 12,
        size: config.mercurySize ?? 0.18,
        speed: config.mercurySpeed ?? 1.6,
        tiltX: config.mercuryTiltX ?? 0,
        tiltZ: config.mercuryTiltZ ?? 7,
        startAngle: config.mercuryStartAngle ?? 15,
        color: 0x9b8b7a,
    },
    {
        name: "Venus",
        displayname: "Vênus",
        texture: config.venusTexture,
        dist: config.venusDist ?? 18,
        size: config.venusSize ?? 0.34,
        speed: config.venusSpeed ?? 1.2,
        tiltX: config.venusTiltX ?? 0,
        tiltZ: config.venusTiltZ ?? 3,
        axisTiltZ: config.venusAxisTiltZ ?? 0,
        rotationDirection: config.venusRotationDirection ?? -1,
        startAngle: config.venusStartAngle ?? 75,
        color: 0xd8b26a,
    },
    {
        name: "Earth",
        displayname: "Terra",
        texture: config.earthTexture,
        dist: config.earthDist ?? 24,
        size: config.earthSize ?? 0.36,
        speed: config.earthSpeed ?? 1,
        tiltX: config.earthTiltX ?? 0,
        tiltZ: config.earthTiltZ ?? 0,
        startAngle: config.earthStartAngle ?? 150,
        color: 0x4f8bd8,
    },
    {
        name: "Mars",
        displayname: "Marte",
        texture: config.marsTexture,
        dist: config.marsDist ?? 31,
        size: config.marsSize ?? 0.28,
        speed: config.marsSpeed ?? 0.8,
        tiltX: config.marsTiltX ?? 0,
        tiltZ: config.marsTiltZ ?? 1.8,
        startAngle: config.marsStartAngle ?? 220,
        color: 0xb65a3a,
    },
    {
        name: "Saturn",
        displayname: "Saturno",
        texture: config.saturnTexture,
        dist: config.saturnDist ?? 62,
        size: config.saturnSize ?? 0.9,
        speed: config.saturnSpeed ?? 0.3,
        tiltX: config.saturnTiltX ?? 0,
        tiltZ: config.saturnTiltZ ?? 2.5,
        startAngle: config.saturnStartAngle ?? 300,
        color: 0xc9ad7a,
    },
    {
        name: "Uranus",
        displayname: "Urano",
        texture: config.uranusTexture,
        dist: config.uranusDist ?? 78,
        size: config.uranusSize ?? 0.65,
        speed: config.uranusSpeed ?? 0.2,
        tiltX: config.uranusTiltX ?? 0,
        tiltZ: config.uranusTiltZ ?? 0.8,
        axisTiltZ: config.uranusAxisTiltZ ?? 97.77,
        rotationDirection: config.uranusRotationDirection ?? -1,
        startAngle: config.uranusStartAngle ?? 35,
        color: 0x80c7d8,
    },
    {
        name: "Neptune",
        displayname: "Netuno",
        texture: config.neptuneTexture,
        dist: config.neptuneDist ?? 95,
        size: config.neptuneSize ?? 0.65,
        speed: config.neptuneSpeed ?? 0.15,
        tiltX: config.neptuneTiltX ?? 0,
        tiltZ: config.neptuneTiltZ ?? 1.8,
        startAngle: config.neptuneStartAngle ?? 115,
        color: 0x385bd8,
    },
]

export const getJupiterMoonConfigs = (config) => [
    {
        name: "Callisto",
        displayname: "Calisto",
        textureUrl: config.callistoTexture,
        radius: config.callistoRadius ?? DEFAULT_SYSTEM.Callisto.radius,
        position: [
            config.callistoX ?? DEFAULT_SYSTEM.Callisto.position[0],
            config.callistoY ?? DEFAULT_SYSTEM.Callisto.position[1],
            config.callistoZ ?? DEFAULT_SYSTEM.Callisto.position[2],
        ],
        color: DEFAULT_SYSTEM.Callisto.color,
    },
    {
        name: "Europa",
        displayname: "Europa",
        textureUrl: config.europaTexture,
        radius: config.europaRadius ?? DEFAULT_SYSTEM.Europa.radius,
        position: [
            config.europaX ?? DEFAULT_SYSTEM.Europa.position[0],
            config.europaY ?? DEFAULT_SYSTEM.Europa.position[1],
            config.europaZ ?? DEFAULT_SYSTEM.Europa.position[2],
        ],
        color: DEFAULT_SYSTEM.Europa.color,
    },
    {
        name: "Ganymede",
        displayname: "Ganimedes",
        textureUrl: config.ganymedeTexture,
        radius: config.ganymedeRadius ?? DEFAULT_SYSTEM.Ganymede.radius,
        position: [
            config.ganymedeX ?? DEFAULT_SYSTEM.Ganymede.position[0],
            config.ganymedeY ?? DEFAULT_SYSTEM.Ganymede.position[1],
            config.ganymedeZ ?? DEFAULT_SYSTEM.Ganymede.position[2],
        ],
        color: DEFAULT_SYSTEM.Ganymede.color,
    },
    {
        name: "IO",
        textureUrl: config.ioTexture,
        radius: config.ioRadius ?? DEFAULT_SYSTEM.IO.radius,
        position: [
            config.ioX ?? DEFAULT_SYSTEM.IO.position[0],
            config.ioY ?? DEFAULT_SYSTEM.IO.position[1],
            config.ioZ ?? DEFAULT_SYSTEM.IO.position[2],
        ],
        color: DEFAULT_SYSTEM.IO.color,
    },
]
