export const GrainShader = {
    uniforms: {
        tDiffuse: { value: null },
        amount: { value: 0.015 },
        time: { value: 0.0 },
        brightnessProtect: { value: 0.75 },
    },
    vertexShader: [
        "varying vec2 vUv;",
        "void main() {",
        "vUv = uv;",
        "gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);",
        "}",
    ].join("\n"),
    fragmentShader: [
        "uniform sampler2D tDiffuse;",
        "uniform float amount;",
        "uniform float time;",
        "uniform float brightnessProtect;",
        "varying vec2 vUv;",
        "float random(vec2 p) {",
        "return fract(sin(dot(p + time, vec2(12.9898, 78.233))) * 43758.5453);",
        "}",
        "void main() {",
        "vec4 color = texture2D(tDiffuse, vUv);",
        "float luminance = dot(color.rgb, vec3(0.299, 0.587, 0.114));",
        "float protect = 1.0 - smoothstep(brightnessProtect, 1.0, luminance);",
        "float noise = (random(vUv) - 0.5) * amount * protect;",
        "color.rgb += color.rgb * noise;",
        "gl_FragColor = color;",
        "}",
    ].join("\n"),
}

export const rendererConfig = {
    sunTexture: "/textures/01 sun.webp",
    mercuryTexture: "/textures/02 mercury.jpg",
    venusTexture: "/textures/03venus.jpg",
    earthTexture: "/textures/04earth.jpg",
    earthCloudsTexture: "/textures/04earthClouds.jpg",
    earthMoonTexture: "/textures/04moon.jpg",
    marsTexture: "/textures/05mars.jpg",
    jupiterTexture: "/textures/06jupiter.jpg",
    jupiterInteriorTexture: "/textures/06jupiterInterior.png",
    ioTexture: "/textures/06jupiterIo.jpg",
    europaTexture: "/textures/06jupiterEuropa.jpg",
    ganymedeTexture: "/textures/06jupiterGanymede.jpg",
    callistoTexture: "/textures/06jupiterCalisto.jpg",
    ringTexture: "/textures/06jupiterRings.png",
    saturnTexture: "/textures/07saturn.jpg",
    saturnRingTexture: "/textures/07saturnRings.png",
    uranusTexture: "/textures/08uranus.jpg",
    uranusRingTexture: "/textures/08uranosRings.png",
    neptuneTexture: "/textures/09neptune.jpg",
    neptuneRingTexture: "/textures/09neptuneRings.png",
    sunGlowTexture: "/textures/sunLeak.jpg",
    sunFlareTexture: "/textures/sunLeak.jpg",
    sunFlareIntensity: 1.2,
    sunFlareMainSize: 300,
    sunFlareGhost1Size: 48,
    sunFlareGhost2Size: 70,
    sunFlareGhost3Size: 100,
    sunFlareGhost4Size: 52,
    sunFlareSpriteSize: 18,
    sunFlareBrightness: 0.75,
    hudHideViewportHeight: 0.3,
    sunIntensity: 0.5,
    bloomStrength: 0.13,
    bloomRadius: 0.35,
    bloomThreshold: 0.05,
    ambientIntensity: 0,
    orbitSpeed: 1,
    rotateSpeed: 1,
    autoRotate: 1,
    showText: 1,
    dotSize: 8,
    dotColor: "rgba(255,255,255,0.95)",
    dotGlow: 12,
    showPulse: true,
    labelFontFamily: "system-ui, sans-serif",
    labelFontSize: 11,
    labelFontColor: "white",
    labelLetterSpacing: "0.08em",
    labelUppercase: true,
    hudIntensity: 64,
    planetViewportHeight: 0.7,
    hudZoomTolerance: 0.15,
    moonViewportHeight: 0.5,
    starTravel: {
        starColor: "#FFFFFF",
        starCount: 300,
        starSize: 2,
        intensity: 100,
        baseSpeed: 0.2,
        hueVariation: 0,
        mouseInfluence: 0.08,
    },
    scenes: [],
    customMarkers: [],
}
