export const GrainShader = {
    uniforms: {
        tDiffuse: { value: null },
        amount: { value: 0.015 },
        time: { value: 0.0 },
        brightnessProtect: { value: 0.75 },
    },
    vertexShader: [
        "varying vec2 vUv;",
        "void main() {",
        "vUv = uv;",
        "gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);",
        "}",
    ].join("\n"),
    fragmentShader: [
        "uniform sampler2D tDiffuse;",
        "uniform float amount;",
        "uniform float time;",
        "uniform float brightnessProtect;",
        "varying vec2 vUv;",
        "float random(vec2 p) {",
        "return fract(sin(dot(p + time, vec2(12.9898, 78.233))) * 43758.5453);",
        "}",
        "void main() {",
        "vec4 color = texture2D(tDiffuse, vUv);",
        "float luminance = dot(color.rgb, vec3(0.299, 0.587, 0.114));",
        "float protect = 1.0 - smoothstep(brightnessProtect, 1.0, luminance);",
        "float noise = (random(vUv) - 0.5) * amount * protect;",
        "color.rgb += color.rgb * noise;",
        "gl_FragColor = color;",
        "}",
    ].join("\n"),
}

export const assetUrl = (path) => `${import.meta.env.BASE_URL}${path}`

export const rendererConfig = {
    sunTexture: assetUrl("textures/01 sun.webp"),
    mercuryTexture: assetUrl("textures/02 mercury.jpg"),
    venusTexture: assetUrl("textures/03venus.jpg"),
    earthTexture: assetUrl("textures/04earth.jpg"),
    earthCloudsTexture: assetUrl("textures/04earthClouds.jpg"),
    earthMoonTexture: assetUrl("textures/04moon.jpg"),
    marsTexture: assetUrl("textures/05mars.jpg"),
    jupiterTexture: assetUrl("textures/06jupiter.jpg"),
    jupiterInteriorTexture: assetUrl("textures/06jupiterInterior.png"),
    ioTexture: assetUrl("textures/06jupiterIo.jpg"),
    europaTexture: assetUrl("textures/06jupiterEuropa.jpg"),
    ganymedeTexture: assetUrl("textures/06jupiterGanymede.jpg"),
    callistoTexture: assetUrl("textures/06jupiterCalisto.jpg"),
    ringTexture: assetUrl("textures/06jupiterRings.png"),
    saturnTexture: assetUrl("textures/07saturn.jpg"),
    saturnRingTexture: assetUrl("textures/07saturnRings.png"),
    uranusTexture: assetUrl("textures/08uranus.jpg"),
    uranusRingTexture: assetUrl("textures/08uranosRings.png"),
    neptuneTexture: assetUrl("textures/09neptune.jpg"),
    neptuneRingTexture: assetUrl("textures/09neptuneRings.png"),
    sunGlowTexture: assetUrl("textures/sunLeak.jpg"),
    sunFlareTexture: assetUrl("textures/sunLeak.jpg"),
    sunFlareIntensity: 1.2,
    sunFlareMainSize: 300,
    sunFlareGhost1Size: 48,
    sunFlareGhost2Size: 70,
    sunFlareGhost3Size: 100,
    sunFlareGhost4Size: 52,
    sunFlareSpriteSize: 18,
    sunFlareBrightness: 0.75,
    planetBacklightEmissive: 0.12,
    hudHideViewportHeight: 0.2,
    sunIntensity: 0.5,
    bloomStrength: 0.1,
    bloomRadius: 0.35,
    bloomThreshold: 0.08,
    ambientIntensity: 0,
    orbitSpeed: 1,
    rotateSpeed: 1,
    autoRotate: 1,
    showText: 1,
    dotSize: 8,
    dotColor: "rgba(255,255,255,0.95)",
    dotGlow: 12,
    showPulse: true,
    labelFontFamily: "system-ui, sans-serif",
    labelFontSize: 11,
    labelFontColor: "white",
    labelLetterSpacing: "0.08em",
    labelUppercase: true,
    hudIntensity: 64,
    planetViewportHeight: 0.7,
    hudZoomTolerance: 0.15,
    moonViewportHeight: 0.5,
    greatRedSpotViewportHeight: 1.08,
    greatRedSpotTextureU: 0.365,
    greatRedSpotTextureV: 0.625,
    greatRedSpotSurfaceOffset: 0.98,
    greatRedSpotRotationY: -124,
    greatRedSpotTurnSpeed: 0.08,
    starTravel: {
        starColor: "#FFFFFF",
        starCount: 300,
        starSize: 2,
        intensity: 100,
        baseSpeed: 0.2,
        hueVariation: 0,
        mouseInfluence: 0.08,
    },
    scenes: [],
    customMarkers: [],
}
